[build]
builder = "NIXPACKS"

[deploy]
startCommand = """
    alembic upgrade head &&
    python -m brew_scout
        --database_dsn postgresql+asyncpg://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
        --telegram_api_url ${TELEGRAM_API_URL}
        --telegram_api_token ${TELEGRAM_API_TOKEN}
"""
numReplicas = 1
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3