"""usr

Revision ID: af8df38b63e8
Revises: 9ec756593897
Create Date: 2024-05-19 16:16:43.200487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "af8df38b63e8"
down_revision = "9ec756593897"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tuid", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(128), nullable=False),
        sa.Column("first_name", sa.String(128), nullable=True),
        sa.Column("last_name", sa.String(128), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=False, unique=False, server_default=sa.text("false")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "tuid"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
